version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
  settings:
    revive:
      # everything not explicitly enabled below is disabled
      rules:
        # style & naming
        - name: exported
          disabled: false
        - name: var-naming
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: var-declaration
          disabled: false

        # error handling
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: error-naming
          disabled: false
        - name: errorf
          disabled: false

        # control flow & code quality
        - name: if-return
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: superfluous-else
          disabled: false
        - name: empty-block
          disabled: false
        - name: unreachable-code
          disabled: false

        # import & context rules
        - name: blank-imports
          disabled: false
        - name: dot-imports
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: context-keys-type
          disabled: false

        # misc best practices
        - name: increment-decrement
          disabled: false
        - name: range
          disabled: false
        - name: time-naming
          disabled: false
        - name: unexported-return
          disabled: false
        - name: unused-parameter
          disabled: false
        - name: redefines-builtin-id
          disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
